spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: "sdfjhsdjkfgdksfgd"
#      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      enable-auto-commit: false
      auto-offset-reset: latest
    properties:
      schema.registry.url: "http://localhost:8089"
      spring:
        deserializer:
          key:
            delegate:
              class: io.confluent.kafka.serializers.KafkaAvroDeserializer
          value:
            delegate:
              class: io.confluent.kafka.serializers.KafkaAvroDeserializer

