spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: "sdfjhsdjkfgdksfgd"
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      enable-auto-commit: false
      auto-offset-reset: latest
    properties:
      schema.registry.url: "http://localhost:8081"
      spring:
        deserializer:
          key:
            delegate:
              class: org.apache.kafka.common.serialization.StringDeserializer
          value:
            delegate:
              class: org.apache.kafka.common.serialization.IntegerDeserializer
    dlt:
      enable: true

