spring:
  application:
    name: kafka-producer-spring-boot

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      value-serializer: org.apache.kafka.common.serialization.IntegerSerializer